### PR TITLE
Initial Heroku Setup

### PR DESCRIPTION
**Pull request by czue**
This has been used to set up https://mpact.herokuapp.com/. However, web sockets don't appear to be working yet.

(I edited this to remove the other issues, which were resolved by making the bot an admin on the groups and merging master)

Additionally, Heroku's free tier doesn't allow us to run more than one worker, so we can't run celery. This means the scheduled messages aren't working/setup. Perhaps we could set up a Dimagi heroku account so we can pay for that (at least for the demo)? 

Recommend reviewing all at once, since I had to debug by pushing code to heroku every commit.

### CODE REVIEW

**Comment by czue** [comment]
@bderenzi I think this is ready

**Review by bderenzi — APPROVED** [review]
Super

**Review by kaapstorm — APPROVED** [review]
:rocket:

**Comment by kaapstorm** [comment]
This is cool!
image

**Pull request merged**
