### PR TITLE
Separate files for RTD

### PR DESCRIPTION
**Pull request by kaapstorm**
Turns out, ReadTheDocs must have a table of contents to work, and the table of contents must have separate files to work.

This branch resolves RTD builds that say they succeed but HTML documentation just returns a 404.

Documentation is hosted here: https://uw-mpact.readthedocs.io/

### CODE REVIEW

**Comment by bderenzi** [comment]
I'm of two minds here. I found the single page docs to be a bit easier since each topic is so short. There's no way to have a single page and have index things jump between different sections? 

Looking at their docs:
https://docs.readthedocs.io/en/stable/choosing-a-site.html

It looks like with headers and subheaders you can get navigation?

**Comment by kaapstorm** [comment]
I also far prefer having the documentation in a single file, for the same reason as you.

An alternative is just to revert the commit that converts to reStructuredText, and point users to reading the documentation on GitHub. (I have a branch for this already, in case I couldn't fix the RTD issue.)

> There's no way to have a single page and have index things jump between different sections?

Maybe there is, but I don't know it, and I couldn't find it. But if you have more luck than I did, I'd love to know the solution, and I'd be happy to use it.

> It looks like with headers and subheaders you can get navigation?

Yes, we have navigation using headings and subheadings -- e.g. https://uw-mpact.readthedocs.io/scheduling.html -- so I don't think that this is where the problem is. Interestingly, RTD successfully builds a PDF of the docs, with a table of contents that includes the headings from the same file. It's just the HTML that has a problem. RTD shows a 404 page, and doesn't explain why in the build logs.

**Comment by czue** [comment]
Maybe a compromise would be to just have a small number of pages, e.g. a "user guide" and a "developer/sysadmin guide"?

Then we can have a basic ToC and also have most of the relevant content live on single pages.

**Comment by czue** [comment]
did you change something on the hosted site? seems like it's now working how we want?

Edit: guessing this is https://github.com/dimagi/mpact/pull/52/

**Comment by kaapstorm** [comment]
> Edit: guessing this is #52

Yes, that's exactly it. Cool, I'll close this, and go with #52

**Pull request closed without merging**
